@echo off
echo Batch file is starting...
echo CD'ing into the current directory the bat file started in.
cd %~dp0
echo Starting download for Steam library game covers!
echo Downloading 600x900.jpg game covers...
python steam_librarycache_600x900.py
echo Now downloading 600x900_2x.jpg covers...
python steam_librarycache_600x900_2x.py
echo Now downloading header.jpg covers...
python steam_librarycache_header.py
echo Now downloading hero.jpg covers...
python steam_librarycache_hero.py
echo Now downloading hero_blur.jpg covers...
python steam_librarycache_hero_blur.py
echo Now downloading icon.jpg covers...
python steam_librarycache_icon.py
echo Now downloading logo.png covers...
python steam_librarycache_logo.py
echo Finished downloadong all available game covers from player's library!
pause